### ISSUE TITLE
Mistake in the City

### ISSUE THREAD

**Issue by praveenscience** [rahul-gore-temp/opensource-website-for-rahul#1]
Hey Rahul, we are from Vidyalankar and not Vellore. This needs to be fixed.

**Comment by praveenscience** [comment]
And @rahul-gore-temp, I am happy to work on this! 😊

**Comment by Rutuja0511** [comment]
I want to work on this.

**Comment by praveenscience** [comment]
Thanks @rahul-gore-temp I am going to start working on this.
